module.exports = {
  content: ["./src/**/*.{jsx, css}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {'blue-purple': '#312682', 'light-gray': '#c8c9ce', 'white': '#ffffff', 'dark-gray': 'rgb(68 64 60)' },
    fontFamily: {'roboto': 'Roboto'},
    fontSize: { '6xs': '2px',
                '5xs': '4px',
                '4xs': '6px',
                '3xs': '8px',
               '2xs': '10px',
               'xs': '.75rem',
               'xsm': '13px',
               'sm': '.875rem',
               'm': '14px',
               'tiny': '.875rem',
               'base': '1rem',
               'lg': '1.125rem',
               'xl': '1.25rem',
               '2xl': '1.5rem',
               '3xl': '1.875rem',
               '4xl': '2.25rem',
               '5xl': '3rem',
               '6xl': '4rem',
               '7xl': '5rem'},
    borderWidth: { DEFAULT: '1px',
                   '1': '1.5px',
                   '2': '2px',
                   '3': '3px',
                   '4': '4px',
                   '6': '6px',
                   '8': '8px'},
    screens: {  
      'xxs': '320px',
      'xs': '425px',
      'xsm': '560px',
      'sm': '640px',
      'lsm': '820px',
      'md': '1024px',
      'lg': '1280px',
      '2xl':'2560px',
    },
    extend: {
      maxWidth: {
        'readable': '30ch',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
  ],
}
